services:
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - "./app:/usr/src/app"
      - "./helper-scripts:/usr/src/helper-scripts"
      - "./tmp:/usr/src/tmp"
    env_file:
      - .env
